### ISSUE TITLE
Mastodon may freeze with overlay visibility track of focused vertex

### ISSUE THREAD

**Issue by stefanhahmann** [mastodon-sc/mastodon#295] opened 2024-03-13 16:56 UTC
## Steps to reproduce

1. Create a new Mastodon project using https://github.com/mastodon-sc/mastodon-example-data/blob/master/tgmm-mini/datasethdf5.xml and https://github.com/mastodon-sc/mastodon-example-data/blob/master/tgmm-mini/datasethdf5.h5
2. Open BDV
3. Track a few spots using `a` button in the BDV
4. Ensure that last tracked spot is focused and highlighted (i.e. pink + solid line, cf. video below) and the mouse pointer is inside this spot.
5. **Stop moving the mouse**
6. Use button `v` to set Overlay visibility to Track of focused vertex
7. Press button `a` 
8. Mastodon is now "Frozen", i.e. Menus cannot be accessed anymore. Even Fiji cannot be closed properly.

![GIF 13 03 2024 17-59-21](https://github.com/mastodon-sc/mastodon/assets/10515534/7a3ab120-678c-4ec3-a4bf-1dd888727fe9)

**Comment by tinevez** [comment] 2024-03-14 11:16
I could not reproduce with beta-29 on Mac or on Windows. 
Could you try with a 'fresh' Fiji? Or on another computer?

**Comment by stefanhahmann** [comment] 2024-03-14 12:56
> I could not reproduce with beta-29 on Mac or on Windows. Could you try with a 'fresh' Fiji? Or on another computer?

I could reproduce the bug yesterday on three independent machine (2 windows, 1 ubuntu) with beta-29. I could just reproduce it again with a 'fresh' Fiji and beta-29. I added one more step to the steps to reproduce description to make the steps more precise.

**Comment by tinevez** [comment] 2024-03-15 09:52
I could reproduce the bug! Thanks for your accurate step description.
Apparently not moving the mouse is important to have the bug. This hints an issue with not having a focused vertex when the mode is selected. I tried to check that happened to the 'focus' using a TrackScheme window on the side.

My best guess would be that the crash is actually linked to NOT having a focused vertex, when the display mode 'Track of focused vertex' is selected. 

I will check what happens when the visibility mode is changed in this case. A first suspect to interrogate would be:
https://github.com/mastodon-sc/mastodon/blob/master/src/main/java/org/mastodon/views/bdv/overlay/Visibilities.java#L329

**Comment by stefanhahmann** [comment] 2024-03-15 11:46
> My best guess would be that the crash is actually linked to NOT having a focused vertex, when the display mode 'Track of focused vertex' is selected.

Yes, exactly. This is reason, which causes the freeze / deadlock.

My PR (https://github.com/mastodon-sc/mastodon/issues/295), which suppresses the problem feels more like a workaround than a real solution.

**Comment by stefanhahmann** [comment] 2024-03-15 11:47
> I will check what happens when the visibility mode is changed in this case. A first suspect to interrogate would be: https://github.com/mastodon-sc/mastodon/blob/master/src/main/java/org/mastodon/views/bdv/overlay/Visibilities.java#L329

I also have the impression that the line you mention in conjunction with https://github.com/mastodon-sc/mastodon/blob/373a2a95901c0d496a18a78b4a5ee37ada822a7b/src/main/java/org/mastodon/views/bdv/overlay/Visibilities.java#L338 causes the problem.

**Comment by stefanhahmann** [comment] 2024-06-04 11:21
@tinevez I noticed that you have merged https://github.com/mastodon-sc/mastodon/pull/297 which was targeted to circumvent the bug described in this issue. I would suggest to close this issue, unless you are still up for a better solution to it?

**Comment by tinevez** [comment] 2024-06-04 11:46
No this is the right fix for this bug.

**Closed by tinevez** 2024-06-04 11:46 UTC
Labels: bug
